---
sidebar: sidebar 
permalink: deploy/qsg_10.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: Proporciona instrucciones para poner en marcha e inicializar herramientas de ONTAP para VMware vSphere. 
---
= Herramientas de ONTAP para VMware vSphere Quick Start
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Herramientas de ONTAP para VMware vSphere es un único complemento vCenter Server que incluye herramientas ONTAP y extensiones VASA Provider. Las herramientas de ONTAP se recomiendan para todos los entornos de ONTAP vSphere, ya que configuran los ajustes del host ESXi y aprovisionan el almacenamiento de ONTAP mediante prácticas recomendadas. El proveedor VASA se requiere para el soporte de volúmenes virtuales (vVols).



== Preparación de la instalación

Pone en marcha el complemento como dispositivo virtual, lo que reduce el esfuerzo de instalar y registrar cada producto por separado en vCenter Server.



=== Requisitos de puesta en marcha

Antes de implementar las herramientas ONTAP para VMware vSphere, debe estar familiarizado con los requisitos de espacio para el paquete de puesta en marcha y algunos requisitos básicos del sistema host.

Las herramientas de ONTAP se pueden usar con un servidor Windows vCenter Server o con un servidor vCenter Server VirtualAppliance (vcsa) de VMware. Debe implementar las herramientas de ONTAP en una instancia de vSphere compatible que incluya el sistema ESXi.

* * Requisitos de espacio del paquete de instalación por nodo*
+
** 10 GB para instalaciones con Thin Provisioning
** 200 GB para instalaciones con aprovisionamiento pesado


* * Requisitos de tamaño del sistema host por nodo*
La memoria recomendada según el tamaño de la implementación y por nodo se muestra en la tabla siguiente:


|===


| Tipo de despliegue | CPU | Memoria (GB) 


| Pequeño (S) | 8 | 16 


| Medio (M) | 12 | 24 


| Grande (L) | 16 | 32 
|===


== Requisitos mínimos de almacenamiento y aplicaciones:

|===
| Almacenamiento, host y aplicaciones | Requisitos de versión 


| ONTAP | ONTAP 9.10.1 , 9,11 , 9,12 y 9,13 


| VSphere de VMware | La versión mínima admitida de VMware es 7,0.3. 


| Hosts ESXi | ESXi 7.0.3 o versión posterior 


| El servidor de vCenter | VCenter 7.0.3 


| Proveedor de VASA | 3,0 


| Aplicación ova | 10,0 
|===
Para obtener más información, consulte link:../deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html["Requisitos para poner en marcha las herramientas de ONTAP"]



=== Requisitos de las herramientas de ONTAP

* Configurar y configurar el entorno de vCenter Server.
* Descargue el archivo .ova.
* Las credenciales de inicio de sesión para la instancia de vCenter Server.
* Elimine la caché del explorador para evitar cualquier problema con la caché del explorador durante la implementación de las herramientas de ONTAP.
* Configure la puerta de enlace predeterminada que utilizará el dispositivo virtual para responder a los ping ICMP.
* Un nombre de host DNS válido para el dispositivo virtual.




== Implementar las herramientas de ONTAP

.Pasos
. Descargue `.zip` archivo que contiene binarios y certificados firmados de la https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^] En un sistema vSphere Client para implementar las herramientas de ONTAP.
. Extraiga el `.zip` archive e implemente el `.ova` archivo.
. Inicie sesión en vSphere Server.
. Desplácese hasta el pool de recursos o el host en el que desea implementar el OVA.
. Haga clic con el botón derecho en el centro de datos requerido y seleccione *Implementar plantilla OVF...*.
. Puede introducir la URL del archivo .ova o ir a la carpeta donde se guarda el archivo .ova y, a continuación, seleccionar *Siguiente*.
. Especifique los detalles necesarios para completar la implementación.


Puede ver el progreso de la implementación en la pestaña Tareas y esperar a que se complete la implementación.
