---
permalink: manage/manage_vcenter.html 
sidebar: sidebar 
keywords:  
summary: Las instancias de vCenter son plataformas de gestión central que le permiten controlar hosts, equipos virtuales y back-ends de almacenamiento. 
---
= Gestión de vCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las instancias de vCenter son plataformas de gestión central que le permiten controlar hosts, equipos virtuales y back-ends de almacenamiento.



== Añada vCenter

Puede añadir y gestionar varios vCenter con una instancia de herramientas de ONTAP para VMware vCenter 10,0.

* Pasos*

. Iniciar `\https://loadBalanceIP:8443/virtualization/ui/` Desde el explorador con las credenciales de administrador de las herramientas de ONTAP proporcionadas durante la implementación.
. Seleccione vCenters en la barra lateral
. Seleccione *ADD* para los vCenters integrados con la dirección IP/nombre de host de vCenter, nombre de usuario, contraseña y puerto.
. Navegue a la página *Backend de almacenamiento* y seleccione *Agregar al backend de almacenamiento integrado* (Clúster de ONTAP) con nombre de host, nombre de usuario, contraseña y puerto.


Consulte link:../configure/task_configure_user_role_and_privileges.html["Lista de privilegios mínimos necesarios para el usuario de cluster de ámbito global no administrativo"].



== Asocie o disocie el back-end del almacenamiento con vCenter

La página enumerada de vCenter muestra el número de back-ends de almacenamiento asociados. Cada vCenter tiene la opción de asociar o desasociar un back-end de almacenamiento
Esta tarea le ayuda a crear un mapeo entre el back-end de almacenamiento y la vCenter incorporada a nivel global.

* Pasos*

. Iniciar `\https://loadBalanceIP:8443/virtualization/ui/` Desde el explorador con las credenciales de administrador de las herramientas de ONTAP proporcionadas durante la implementación.
. Seleccione vCenters en la barra lateral.
. Haga clic en los tres puntos verticales en la instancia de vCenter que desea asociar o disociar con los back-ends de almacenamiento.
. Selecciona *Asociar o disociar backend de almacenamiento* dependiendo de la acción que quieras realizar.
+
Consulte link:../configure/task_configure_user_role_and_privileges.html["Lista de privilegios mínimos necesarios para el usuario de cluster de ámbito global no administrativo"].





== Modifique vCenter

Siga los pasos que se indican a continuación para modificar los vCenters.

. Iniciar `\https://loadBalanceIP:8443/virtualization/ui/` Desde el explorador con las credenciales de administrador de las herramientas de ONTAP proporcionadas durante la implementación.
. Seleccione vCenters en la barra lateral
. Haga clic en los puntos suspensivos verticales en el vCenter que desea modificar y seleccione *Modify*.
. Modifique los detalles de vCenter y seleccione *Modify*.




== Quite vCenter

Debe quitar todos los back-ends de almacenamiento conectados a la instancia de vCenter antes de quitarlo.

. Iniciar `\https://loadBalanceIP:8443/virtualization/ui/` Desde el explorador con las credenciales de administrador de las herramientas de ONTAP proporcionadas durante la implementación.
. Seleccione vCenters en la barra lateral
. Haga clic en los puntos suspensivos verticales contra el vCenter que desea quitar y seleccione *Quitar*.
+

NOTE: Una vez que se quita el vCenter, la aplicación ya no lo mantendrá.





== Gestionar umbral de almacenamiento

Use la siguiente API de umbral de obtención para recuperar los límites de umbral de almacenamiento configurados para el volumen y el agregado.

[listing]
----
GET​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----
Ejemplos:
Obtenga los umbrales de almacenamiento por guid de vcenter

[listing]
----
GET "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
----
Utilice la siguiente alarma de configuración de PARCHES para volumen y agregado para generar notificaciones cuando se alcancen los límites de umbral configurados.

[listing]
----
PATCH​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----
Ejemplos:
Actualice los umbrales de almacenamiento por guid de vcenter por vcenter. Los límites predeterminados son del 80% para casi completo y del 90% para completo.
Modificación de todos los valores de umbral

[listing]
----
{{{}PATCH "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
Request Body
{
"volume":

{ "nearly_full_percent": 80, "full_percent": 90 }
,
"aggregate": {
"nearly_full_percent": 80,
"full_percent": 90
}
}{}}}{}
----