---
permalink: manage/task_mount_a_vvols_datastore.html 
sidebar: sidebar 
keywords: Mount vVol 
summary: 'Puede montar un almacén de datos VMware Virtual Volumes \(vVols\) en uno o varios hosts adicionales utilizando el cuadro de diálogo Mount vVols Datastore. El montaje del almacén de datos permite acceder al almacenamiento a hosts adicionales. También es posible desmontar el almacén de datos de vVols.' 
---
= Montar y desmontar un almacén de datos de vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un almacén de datos VMware Virtual Volumes (vVols) se puede montar en uno o varios hosts adicionales mediante el cuadro de diálogo Mount vVols Datastore. El montaje del almacén de datos permite acceder al almacenamiento a hosts adicionales. También es posible desmontar el almacén de datos de vVols.

Use la siguiente API para montar o desmontar un almacén de datos vVols.
Debe pasar x-auth para la API. Puede generar esta x-auth desde la nueva API que se añadió en Auth en Swagger.

[listing]
----
/virtualization/api/v1/auth/vcenter-login
----
[listing]
----
PATCH
/virtualization/api/v1/vcenters/{vcguid}/vvols/datastores/{moref}/hosts
----
Obtenga el moref del almacén de datos VVol desde vCenter.

Cuerpo de la solicitud

[listing]
----
{
  "operation": "mount",
  "morefs": [
    "host-7044"
  ],
}
----


== Ejemplos:

* Montar en host adicional


Use la siguiente API para montarla en host adicional:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "mount",
      "morefs": ["host-13"],
     }
----
* Desmonte en host adicional


Use la siguiente API para desmontarla en el host adicional:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "unmount",
      "morefs": ["host-13"],
     }
----